# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Uniuni_Driver' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MapboxMaps', '10.6.0'
  pod 'MapboxNavigation', '~> 2.6'

  target 'Uniuni_DriverTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
