//
//  StringLocalizationExtension.swift
//  Uniuni_Driver
//
//  Created by Boqian Cheng on 2022-06-18.
//

import Foundation

extension String {
    static let deliveryStr: String = NSLocalizedString("Delivery", comment: "")
    static let scanStr: String = NSLocalizedString("Scan", comment: "")
    static let incomeStr: String = NSLocalizedString("Income", comment: "")
    static let deliveringStr: String = NSLocalizedString("Delivering", comment: "")
    static let undeliveredStr: String = NSLocalizedString("Undelivered", comment: "")
    static let dateStr: String = NSLocalizedString("Date", comment: "")
    static let routeStr: String = NSLocalizedString("Route", comment: "")
    static let distanceStr: String = NSLocalizedString("Distance", comment: "")
    static let sortListByStr: String = NSLocalizedString("Sort_List_By", comment: "")
    static let searchStr: String = NSLocalizedString("Search", comment: "")
    static let wrongAddressStr: String = NSLocalizedString("Wrong Address", comment: "")
    static let regularStr: String = NSLocalizedString("Regular", comment: "")
    static let expressStr: String = NSLocalizedString("Express", comment: "")
    static let medicalStr: String = NSLocalizedString("Medical", comment: "")
    static let KMAwayStr: String = NSLocalizedString("KM Away", comment: "")
    static let MIAwayStr: String = NSLocalizedString("MI Away", comment: "")
    static let parcelDetailsStr: String = NSLocalizedString("Parcel Details", comment: "")
    static let navigateToServicePointStr: String = NSLocalizedString("Navigate to Service Point", comment: "")
    static let failedStr: String = NSLocalizedString("Failed", comment: "")
    static let deliveredStr: String = NSLocalizedString("Delivered", comment: "")
    static let orderTypeStr: String = NSLocalizedString("Order Type", comment: "")
    static let assignedTimeStr: String = NSLocalizedString("Assigned Time", comment: "")
    static let deliveryTypeStr: String = NSLocalizedString("Delivery Type", comment: "")
    static let deliveryByStr: String = NSLocalizedString("Delivery by", comment: "")
    static let buzzStr: String = NSLocalizedString("Buzz", comment: "")
    static let noteStr: String = NSLocalizedString("Note", comment: "")
    static let houseStr: String = NSLocalizedString("House", comment: "")
    static let townhouseStr: String = NSLocalizedString("Townhouse", comment: "")
    static let businessStr: String = NSLocalizedString("Business", comment: "")
    static let apartmentStr: String = NSLocalizedString("Apartment", comment: "")
    static let chooseMapStr: String = NSLocalizedString("Choose Map", comment: "")
    static let chooseAnApplicationToStartNavigationStr: String = NSLocalizedString("Choose an application to start navigation", comment: "")
    static let cancelStr: String = NSLocalizedString("Cancel", comment: "")
    static let appleMapStr: String = NSLocalizedString("Apple Map", comment: "")
    static let googleMapStr: String = NSLocalizedString("Google Map", comment: "")
    static let inAppMapStr: String = NSLocalizedString("In-app Map", comment: "")
    static let copyAddressStr: String = NSLocalizedString("Copy Address", comment: "")
    static let setDefaultMapStr: String = NSLocalizedString("Set default map", comment: "")
    static let doYouWantToSetDefaultMapStr = NSLocalizedString("Do you want to set default map", comment: "")
    static let noStr: String = NSLocalizedString("No", comment: "")
    static let yesStr: String = NSLocalizedString("Yes", comment: "")
    static let deliveryAttemptStr: String = NSLocalizedString("Delivery Attempt", comment: "")
    static let markAddressTypeStr: String = NSLocalizedString("Mark Address Type", comment: "")
    static let pleaseChooseAddressTypeStr: String = NSLocalizedString("Please choose address type", comment: "")
    static let googleMapIsNotInstalledStr: String = NSLocalizedString("Google map is not installed", comment: "")
    static let OKStr: String = NSLocalizedString("OK", comment: "")
    static let phoneNumberStr: String = NSLocalizedString("Phone Number", comment: "")
    static let callStr: String = NSLocalizedString("Call", comment: "")
    static let textStr: String = NSLocalizedString("Text", comment: "")
    static let textLanguageStr: String = NSLocalizedString("Text Language", comment: "")
    static let chooseALanguageStr: String = NSLocalizedString("Choose a language", comment: "")
    static let returnedStr: String = NSLocalizedString("returned", comment: "")
    static let dropOffStr: String = NSLocalizedString("Drop off", comment: "")
    static let addressTypeNotUpdatedStr: String = NSLocalizedString("Address type not updated", comment: "")
    static let textTemplateStr: String = NSLocalizedString("Text Template", comment: "")
    static let chooseATemplateYouWantToUseStr: String = NSLocalizedString("Choose a template you want to use", comment: "")
    static let wrongURLStr: String = NSLocalizedString("Wrong URL", comment: "")
    static let badInternetConnectionStr: String = NSLocalizedString("Bad internet connection", comment: "")
    static let sentStr: String = NSLocalizedString("Sent", comment: "")
    static let networkFailureStr: String = NSLocalizedString("Network Failure", comment: "")
    static let pleaseCheckYourNetworkAndRetryStr: String = NSLocalizedString("please check your network and retry", comment: "")
    static let failedSendingMessageStr: String = NSLocalizedString("Failed Sending Message", comment: "")
    static let failToSendAMessageStr: String = NSLocalizedString("Fail to send a message", comment: "")
    static let retryStr: String = NSLocalizedString("Retry", comment: "")
    static let deliveryAttemptValueStr = NSLocalizedString("Delivery attempt value", comment: "")
    static let orderInformationStr = NSLocalizedString("Order Information", comment: "")
    static let customerInformationStr = NSLocalizedString("Customer Information", comment: "")
    static let customerNotesStr = NSLocalizedString("Customer Notes", comment: "")
    static let photosStr = NSLocalizedString("Photos", comment: "")
    static let take2PhotosStr = NSLocalizedString("Take 2 photos", comment: "")
    static let completeStr = NSLocalizedString("Complete", comment: "")
    static let orderNoStr = NSLocalizedString("Order No", comment: "")
    static let trackingNoStr = NSLocalizedString("Tracking No", comment: "")
    static let routeNoStr = NSLocalizedString("Route No", comment: "")
    static let nameStr = NSLocalizedString("Name", comment: "")
    static let addressStr = NSLocalizedString("Address", comment: "")
    static let AppHasNoPermissionToUseTheCameraStr = NSLocalizedString("App has no permission to use the camera", comment: "")
    static let unableToCaptureMediaStr = NSLocalizedString("App has no permission to use the camera", comment: "")
    static let firstPhotoStr = NSLocalizedString("First Photo", comment: "")
    static let secondPhotoStr = NSLocalizedString("Second Photo", comment: "")
    
    
    static let retakeStr = NSLocalizedString("Retake", comment: "")
    static let useStr = NSLocalizedString("Use", comment: "")
}
